name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: checkout-termbox
      run: git submodule update --init
    - name: make-termbox
      run: make -C termbox2 lib
    - name: install-termbox
      run: make -C termbox2 install_lib
    - name: cursed-coin
      run: make cursed-coin
